import type { NodeData } from "../types/index.ts"

export const nodes: NodeData[] = [
    {
      id: 0,
      title: "Otto Cline",
      startDate: new Date("2006-10-24"),
      category: "root",
      description: "material agent in real space",
      primaryRelatedNodes: [1, 7, 3],
      secondaryRelatedNotes: [],
      x: 50,
      y: 50,
    },
    {
      id: 1,
      title: "AI and Search",
      jobName: "KMW Technology",
      startDate: new Date("2026-01-05"),
      category: "job",
      description:
        "Making search work for enterprise companies, researching NLP optimization",
      primaryRelatedNodes: [],
      secondaryRelatedNotes: [],
      x: 40,
      y: 40,
    },
    {
      id: 2,
      title: "CS and Biz Major",
      jobName: "Northeastern",
      startDate: new Date("2024-01-05"),
      category: "education",
      description:
        "Making search work for enterprise companies, researching NLP optimization",
      primaryRelatedNodes: [5],
      secondaryRelatedNotes: [6],
      x: 40,
      y: 70,
    },
    {
      id: 3,
      title: "Page",
      jobName: "NYPL Periodicals",
      startDate: new Date("2023-01-05"),
      endDate: new Date("2024-01-05"),
      category: "job",
      description:
        "Making search work for enterprise companies, researching NLP optimization",
      primaryRelatedNodes: [],
      secondaryRelatedNotes: [],
      x: 62,
      y: 50,
    },
    {
      id: 4,
      title: "Intern / Helper guy",
      jobName: "Zo Computer",
      startDate: new Date("2025-10-01"),
      category: "job",
      description: "Building the logical next step to AGI",
      primaryRelatedNodes: [],
      secondaryRelatedNotes: [],
      x: 50,
      y: 15,
    },
  
    {
      id: 5,
      title: "rev ^_^",
      startDate: new Date("2026-01-05"),
      category: "insig",
      description:
        "Making search work for enterprise companies, researching NLP optimization",
      primaryRelatedNodes: [],
      secondaryRelatedNotes: [],
      x: 32,
      y: 85,
    },
    {
      id: 6,
      title: "1st Place",
      jobName: "Remark + Google Hackathon",
      startDate: new Date("2026-01-05"),
      endDate: new Date("2026-01-05"),
      category: "insig",
      description:
        "Making search work for enterprise companies, researching NLP optimization",
      primaryRelatedNodes: [],
      secondaryRelatedNotes: [],
      x: 45,
      y: 80,
    },
    {
      id: 7,
      title: "Highschool",
      jobName: "BSGE",
      startDate: new Date("2020-01-05"),
      endDate: new Date("2024-06-30"),
      category: "insig",
      description:
        "Making search work for enterprise companies, researching NLP optimization",
      primaryRelatedNodes: [2],
      secondaryRelatedNotes: [],
      x: 42,
      y: 58,
    },
    {
      id: 8,
      title: "Captain",
      jobName: "Sting Robotics",
      startDate: new Date("2020-01-05"),
      endDate: new Date("2024-6-30"),
      category: "insig",
      description:
        "Making search work for enterprise companies, researching NLP optimization",
      primaryRelatedNodes: [7],
      secondaryRelatedNotes: [],
      x: 30,
      y: 60,
    },
    {
      id: 9,
      title: "Ambassador",
      jobName: "Zo Computer",
      startDate: new Date("2025-10-00"),
      category: "job",
      description:
        "Making search work for enterprise companies, researching NLP optimization",
      primaryRelatedNodes: [0, 4],
      secondaryRelatedNotes: [],
      x: 52,
      y: 33,
    },
    {
      id: 10,
      title: "Picture Collection DB",
      startDate: new Date("2025-05-00"),
      endDate: new Date("2025-07-00"),
      category: "project",
      description:
        "Making search work for enterprise companies, researching NLP optimization",
      primaryRelatedNodes: [3],
      secondaryRelatedNotes: [],
      x: 67,
      y: 63,
    },
  ];
  